// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slbuonckmvylqwmmvoug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsYnVvbmNrbXZ5bHF3bW12b3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MzQxODUsImV4cCI6MjA2NzUxMDE4NX0.WJPLGIN-kZXI_rVR8K2VeemHs05fTl5RNXJ0op0YY7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});